version: '3.8'
services:
  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
    ports:
      - 3000:3000
    command: npm start
    env_file:
      - .env

  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    ports:
      - 3500:3500
    command: python main.py
    depends_on:
      - redis
    env_file:
      - .env

  worker:
    build: ./worker
    volumes:
      - ./worker:/usr/src/app
    command: python main.py
    depends_on:
      - redis
    env_file:
      - .env
      
  redis:
    image: redis:alpine
    restart: always
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - 6379:6379
    env_file:
      - .env